export const FETCH_TRASH_REQUEST = "recycleBin/FETCH_TRASH_REQUEST";
export const FETCH_TRASH_SUCCESS = "recycleBin/FETCH_TRASH_SUCCESS";
export const FETCH_TRASH_FAILURE = "recycleBin/FETCH_TRASH_FAILURE";

export const RESTORE_FILE_REQUEST = "recycleBin/RESTORE_FILE_REQUEST";
export const RESTORE_FILE_SUCCESS = "recycleBin/RESTORE_FILE_SUCCESS";
export const RESTORE_FILE_FAILURE = "recycleBin/RESTORE_FILE_FAILURE";

export const PERMANENT_DELETE_REQUEST = "recycleBin/PERMANENT_DELETE_REQUEST";
export const PERMANENT_DELETE_SUCCESS = "recycleBin/PERMANENT_DELETE_SUCCESS";
export const PERMANENT_DELETE_FAILURE = "recycleBin/PERMANENT_DELETE_FAILURE";
