export const CHECK_USER_ROLE_REQUEST = "reviewerAssigned/CHECK_USER_ROLE_REQUEST";
export const CHECK_USER_ROLE_SUCCESS = "reviewerAssigned/CHECK_USER_ROLE_SUCCESS";
export const CHECK_USER_ROLE_FAILURE = "reviewerAssigned/CHECK_USER_ROLE_FAILURE";

export const FETCH_REVIEWERS_REQUEST = "reviewerAssigned/FETCH_REVIEWERS_REQUEST";
export const FETCH_REVIEWERS_SUCCESS = "reviewerAssigned/FETCH_REVIEWERS_SUCCESS";
export const FETCH_REVIEWERS_FAILURE = "reviewerAssigned/FETCH_REVIEWERS_FAILURE";

export const FETCH_REVIEWER_QUESTIONS_REQUEST =
  "reviewerAssigned/FETCH_REVIEWER_QUESTIONS_REQUEST";
export const FETCH_REVIEWER_QUESTIONS_SUCCESS =
  "reviewerAssigned/FETCH_REVIEWER_QUESTIONS_SUCCESS";
export const FETCH_REVIEWER_QUESTIONS_FAILURE =
  "reviewerAssigned/FETCH_REVIEWER_QUESTIONS_FAILURE";

export const FETCH_DOCUMENT_QUESTIONS_REQUEST =
  "reviewerAssigned/FETCH_DOCUMENT_QUESTIONS_REQUEST";
export const FETCH_DOCUMENT_QUESTIONS_SUCCESS =
  "reviewerAssigned/FETCH_DOCUMENT_QUESTIONS_SUCCESS";
export const FETCH_DOCUMENT_QUESTIONS_FAILURE =
  "reviewerAssigned/FETCH_DOCUMENT_QUESTIONS_FAILURE";

export const REMOVE_REVIEWER_QUESTION_REQUEST =
  "reviewerAssigned/REMOVE_REVIEWER_QUESTION_REQUEST";
export const REMOVE_REVIEWER_QUESTION_SUCCESS =
  "reviewerAssigned/REMOVE_REVIEWER_QUESTION_SUCCESS";
export const REMOVE_REVIEWER_QUESTION_FAILURE =
  "reviewerAssigned/REMOVE_REVIEWER_QUESTION_FAILURE";
